{{define "footer"}}
<footer class="navbar-fixed-bottom">
<div class="container">
<div class="row">
    <div class="col-lg-12">
    <div style="text-align:center;margin-top:15px;margin-bottom:50px;">
Copyright &copy; jiftle.github.io, generated by gitmdblog, designed by <a href="https://github.com/jiftle/gitmdblog">jiftle</a>. <a href="https://github.com/jiftle/gitmdblog">[source]</a>
</div>
    </div>
    <!-- /.col-lg-12 -->
</div>
</div>
</footer>
{{end}}